#!/bin/bash

xgettext --language=Python --keyword=_ --output=sc.pot usr/lib/sc/main.py usr/lib/sc/splash.py usr/lib/sc/remove.py usr/bin/mint-search-apt usr/bin/mint-make-cmd usr/bin/mint-synaptic-install
